HOME = os.getenv("HOME")
vim.opt.clipboard = "unnamedplus"
vim.opt.undofile = true
vim.opt.wildmode = { longest = "full", "full" }
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.shiftround = true
vim.opt.hidden = true
vim.opt.relativenumber = true
vim.o.signcolumn = "yes:2"
vim.o.listchars = "tab:▸ ,trail:·"
-- vim.opt.listchars = { tab = '» ', trail = '·', nbsp = '␣' }
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.number = true
vim.opt.termguicolors = true
vim.opt.ignorecase = true
vim.opt.ic = true
vim.opt.smartcase = true
vim.opt.wrap = false
vim.opt.list = true
vim.opt.mouse = "a"
vim.opt.scrolloff = 5
vim.opt.sidescrolloff = 12
vim.opt.exrc = true
vim.opt.updatetime = 600 -- Reduce time for highlighting other references
vim.opt.redrawtime = 13000 -- Allow more time for loading syntax on large files
vim.opt.showmatch = true
vim.opt.showmode = false
vim.opt.swapfile = false
-- vim.opt.completeopt = { "menu", "menuone", "noselect" }
vim.opt.confirm = true
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldtext = "v:lua.vim.treesitter.foldtext()"
-- vim.opt.foldenable = false
vim.opt.foldlevelstart = 40
vim.opt.breakindent = true
vim.opt.cursorline = false
-- vim.opt.shortmess =  -- skip errors on startup
vim.g.go_doc_balloon = 1
vim.g.go_doc_popup_window = 1
vim.g.wiki_root = "~/wiki"
vim.opt.inccommand = "split"
-- vim.opt.formatoptions = { 'j' }

-- " set backup
-- " set backupdir=~/.local/share/nvim/backup//
